### ISSUE TITLE
There is not infra folder usign cli@0.1.22-beta.0

### ISSUE THREAD

**Issue by koichimurakami** [mbc-net/mbc-cqrs-serverless#41]
@baquan1708 
When I create new project using cli@0.1.22-beta.0, I could not find the infra folder.
After I update the cli to 0.1.24-beta.0, I could find the infra folder in the project.

Could you make project using latest template, even I use the old cli version?

**Comment by baquan1708** [comment]
At the moment, the template folder is fixed to the CLI version. 

Let me think of a solution, and then I will discuss it with you.

**Comment by koichimurakami** [comment]
@baquan1708 
How about this following solution:

1. Make a folder in temporary
2. npm install cli
3. copy template
4. clean up the folder

**Comment by koichimurakami** [comment]
@baquan1708 
> I think we could store template in separate repository instead of place it in the cli. This way, we can update the template and the CLI independently.

We have to think about case of Windows. Maybe To get  temporary folder path, it's complicated.
Local folder approch does not seem complicated, it's ok.

**Comment by baquan1708** [comment]
This mean: we does not store template in separate repository. And we need to think about the local folder approach as you discuss in https://github.com/mbc-net/mbc-cqrs-serverless/issues/41#issuecomment-2464407882

I'm sorry. I'm not sure what I understand is correct. Could you please clarify or correct my understanding?

**Comment by koichimurakami** [comment]
Could you implement your approch?

**Comment by baquan1708** [comment]
Yes, I’d be happy to do that.

**Comment by koichimurakami** [comment]
@baquan1708 
I'm sorry I was wrong.
Cli have to download a new version template from npm even if cli is old version.

**Comment by baquan1708** [comment]
@koichimurakami  This is the proposed improvement for the template in CLI.

![image](https://github.com/user-attachments/assets/67c22dbe-9b8b-46e1-a158-3020a9c58b0d)

Could you review it before I proceed with the implementation?

**Comment by koichimurakami** [comment]
@baquan1708 
Thank you. That's what I want.

**Comment by baquan1708** [comment]
@koichimurakami 
I've created a pull request https://github.com/mbc-net/mbc-cqrs-serverless/pull/42 to resolve this bug. Could you please review it?
